version: '3'

services:
    ubuntu:
        container_name: dc-vpn-l2tp-clt
        restart: unless-stopped
        hostname: dc-vpn-l2tp-clt
        privileged: true
        build:
            context: ./build
            dockerfile: Dockerfile.ubuntu
            args:
                IMAGE_VERSION: latest
                ### This VPN Args Need Change In File .env
                VPN_NAME: $VPN_NAME
                VPN_SERVER_IP: $VPN_SERVER_IP
                VPN_USER: $VPN_USER
                VPN_PASSWORD: $VPN_PASSWORD
                VPN_IPSEC_PSK: $VPN_IPSEC_PSK
        volumes:
            - /etc/localtime:/etc/localtime:ro
        networks:
            - dc-net
        ports:
            - 42088:3128

networks:
    dc-net:
        name: dc-net
        ipam:
            driver: default
            ### If need set special IP Net Address
            #config:
            #    - subnet: 172.16.1.0/24
